### ISSUE TITLE
tripal 3 container only allows organism creation?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/docker-containers#12]
really bizarre.  http://localhost:8087/bio_data/add redirects me to http://localhost:8087/bio_data/add/1  and i cant go to /2 etc.

Looking in structure I have other content types.  [We don't have this problem on develoepr site which is using latest tripal. ](http://160.36.205.61:8095/bio_data/add)

**Comment by bradfordcondon** [comment]
I destroyed my container, rebuilt it, and updated tripal to current master.  No dice, something is up.

I have 9 bundles in public.tripal_bundle...

**Comment by almasaeed2010** [comment]
Did you try disabling the “overlay” module?

**Comment by bradfordcondon** [comment]
That resolved it, thanks  (even though i didnt have the overlay in the url!).

**Comment by almasaeed2010** [comment]
Yeah I think the overlay module is messing with the URLs somehow to load everything via Ajax so it’s probably the culprit

**Comment by bradfordcondon** [comment]
i enabled the overlay module on dev, and the bug is not reproduced: http://160.36.205.61:8095/#overlay=bio_data/add

**Comment by almasaeed2010** [comment]
I wonder if this is still happening

**Comment by almasaeed2010** [comment]
Yep still happens on the latest version. I am gonna go ahead and disabled the overlay module by default since I have no idea what is causing it.

**Comment by almasaeed2010** [comment]
Disabling overlay by default doesn't fix it. What could be causing this?

**Comment by bradfordcondon** [comment]
so if i understand you, disabling the module fixes it, but never enabling it doesn't?

**Comment by almasaeed2010** [comment]
It's enabled by default with drupal. But disabling it in the docker build doesn't fix it for some reason.

**Comment by almasaeed2010** [comment]
What the heck! Re-enabling it manually fixed it!

**Comment by almasaeed2010** [comment]
Maybe the disabling should happen after populating the cache/finishing tripal installation?

**Comment by almasaeed2010** [comment]
Yep disabling it after tripal finished installing fixed it.

**Comment by bradfordcondon** [comment]
does this merit a minor core bug report?  i havent had the problem  when reinstalling a vagrant site...

**Comment by almasaeed2010** [comment]
I've had that problem before. And I think it was reported to tripal but I am not sure if the issue is still open.
