### ISSUE TITLE
are the port mappings backwards in example?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/docker-containers#13]
to get my site on 8095 i need to run 

`docker run -itd -p 8095:80 --name t2 statonlab/tripal2`

example is

`docker run -itd -p 80:8080 -p 5432:5432 --name my-container -v .:/modules/my-module statonlab:tripal2`

i think the -p flags are backwards?

Also statonlab:tripal2 needs to be statonlab/tripal2 i think since its the repo not the tag.

**Comment by almasaeed2010** [comment]
Yes they are
