### ISSUE TITLE
error creating gene pages when using filter

### ISSUE THREAD

**Issue by slmcevoy** [statonlab/docker-containers#21]
https://tripal.readthedocs.io/en/latest/user_guide/example_genomics/genomes_genes.html
Creating Gene Pages section
When I try to add the filter as described (filter by organism, nothing else) I get a date field related error
Warning: Illegal string offset 'value' in date_combo_element_process() (line 295 of /var/www/html/sites/all/modules/date/date_elements.inc).
Warning: Cannot assign an empty string to a string offset in date_combo_element_process() (line 295 of /var/www/html/sites/all/modules/date/date_elements.inc).
Warning: Illegal string offset 'value' in date_local_date() (line 145 of /var/www/html/sites/all/modules/date/date_elements.inc).
Notice: Uninitialized string offset: 0 in date_local_date() (line 145 of /var/www/html/sites/all/modules/date/date_elements.inc).
Warning: Illegal string offset 'value' in date_combo_element_process() (line 298 of /var/www/html/sites/all/modules/date/date_elements.inc).
Warning: Cannot assign an empty string to a string offset in date_combo_element_process() (line 298 of /var/www/html/sites/all/modules/date/date_elements.inc).
Warning: implode(): Invalid arguments passed in date_limit_format() (line 2276 of /var/www/html/sites/all/modules/date/date_api/date_api.module).
Warning: Illegal string offset 'value' in date_combo_element_process() (line 295 of /var/www/html/sites/all/modules/date/date_elements.inc).
Warning: Cannot assign an empty string to a string offset in date_combo_element_process() (line 295 of /var/www/html/sites/all/modules/date/date_elements.inc).
Warning: Illegal string offset 'value' in date_local_date() (line 145 of /var/www/html/sites/all/modules/date/date_elements.inc).
Notice: Uninitialized string offset: 0 in date_local_date() (line 145 of /var/www/html/sites/all/modules/date/date_elements.inc).
Warning: Illegal string offset 'value' in date_combo_element_process() (line 298 of /var/www/html/sites/all/modules/date/date_elements.inc).
Warning: Cannot assign an empty string to a string offset in date_combo_element_process() (line 298 of /var/www/html/sites/all/modules/date/date_elements.inc).
Warning: implode(): Invalid arguments passed in date_limit_format() (line 2276 of /var/www/html/sites/all/modules/date/date_api/date_api.module).

**Comment by bradfordcondon** [comment]
hi @slmcevoy thanks for the report.  This is a known tripal issue and not related to the docker.

https://github.com/tripal/tripal/issues/723
