### ISSUE TITLE
psql version too low for some tripal modules

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/docker-containers#22]
Some tripal modules that want to use these containers require postgres 9.3 or higher.  This ships with 9.2.  Can we rebuild the image with a higher psql version?

**Comment by bradfordcondon** [comment]
https://www.linode.com/docs/databases/postgresql/how-to-install-postgresql-relational-databases-on-centos-7/#install-from-the-postgres-repositories

**Comment by laceysanderson** [comment]
Yes, please! This is preventing me from using TripalTest efficiently for my ND Genotypes module (https://travis-ci.org/UofS-Pulse-Binfo/nd_genotypes/builds/507664281) 😞

**Comment by bradfordcondon** [comment]
hey @almasaeed2010 i think this is do-able im just getting confused.


```

# Update the system
RUN set -x \
	&& yum update -y

# Install services
# (Apache2, php7.1, posgtes, curl, git, zip, unzip, supervisor ... etc)
RUN set -x \
 	&& yum install -y wget curl git zip unzip httpd crontabs  \
	&& wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm \
    && wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm \
		wget https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm \
    && rpm -Uvh remi-release-7.rpm epel-release-latest-7.noarch.rpm \
    && yum install -y yum-utils \
    && yum-config-manager --enable remi-php71 \
    && yum update -y \
    && yum install -y mod_php php-mcrypt php-mbstring php-json php-posix php-pgsql \
      				  php-pdo php-xml php-curl php-gd supervisor sudo \
      				  patch which

# Install postgres and create alias

RUN \
yum install -y pgdg-centos96-9.6-3.noarch.rpm epel-release \
 && yum update -y \
&& yum install -y postgresql96-server postgresql96-contrib\
#&&  /usr/pgsql-9.6/bin/postgresql96-setup initdb\
#&& systemctl start postgresql-9.6
#alias!
#&& alias initdb 'intdb-96'

```

I need to adapt this part of the build:

```

# Prepare the Database
RUN set -x \
	&& sudo -u postgres initdb -D /var/lib/pgsql/data \
	&& touch /var/log/pgsql.log \
	&& chown postgres:postgres /var/log/pgsql.log \
	&& sudo -u postgres pg_ctl -D /var/lib/pgsql/data -l /var/log/pgsql.log start \
	&& sleep 3 \
```

but `initdb`, `initdb-9.6` and `initdb-96` aren't commands.  Any ideas?  


Alternatively we could use the centos7 psql 9.6 docker instead:

https://hub.docker.com/r/centos/postgresql-96-centos7/


i tried this container, but i get problems at the drush install step, namely - `ls: cannot access /root/.composer/vendor/bin: No such file or directory` . So the composer vendor bin is installed somewhere else...

**Comment by almasaeed2010** [comment]
PR #23

**Comment by almasaeed2010** [comment]
done 0.2.0
