### ISSUE TITLE
Needed: pre-seeded Tripal 3 container

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/docker-containers#9]
* Container should be latest tripal 3, but then in addition, it should load in the SQL dump of the latest tripal [dev seed data](https://github.com/statonlab/tripal_dev_mini_dataset).

**Comment by bradfordcondon** [comment]
assigning you @almasaeed2010 if you need something to work on.  I took a crude stab here: https://github.com/statonlab/docker-containers/tree/seeded

A WAY more graceful approach than this dump would be to use tripal-python to add the data, but that requires contributing to it (which anthony has encouraged, i just havent had time...)
That said its really needed for the dev pub so it is a priority to get SOMETHING pre-seeded available.

**Comment by bradfordcondon** [comment]
Modules I had to enable to load the full dev seed (and hterefore should also be enabled in the build).

* Tripal_analysis_blast


... to be continued

**Comment by bradfordcondon** [comment]
let's just re-disable the modules once the data is loaded.


I made a container manually (load data, recommit to dockerhub).  For now I think this is just as easy as creating the SQL dump and loading it in that way, considering I have to load in the data from the container either way!

This is the commit (its just to the readme since not code-based) https://github.com/statonlab/docker-containers/commit/837e8ece89c686d48f3df79815b772c033e37c58

**Comment by almasaeed2010** [comment]
Reassigned to you since you already did it 👍

**Comment by bradfordcondon** [comment]
so we should incldue an uncommented version of the seeder here, yes?  and copy it in on install into tripal core perhaps?  And provide an example command in the README for how to run it?

**Comment by bradfordcondon** [comment]
Now that we've updated test suite (see issue ) we only need to move the seeder from `databaseseeders/examples/`  to `databaseseeders` and run it.

**Comment by almasaeed2010** [comment]
We also need to install all of the extension modules required for the dev seeder to succeed (interpro, blast, etc...)

**Comment by bradfordcondon** [comment]
oops, yeah, that too.  quite a few modules actually.

**Comment by bradfordcondon** [comment]
I dont see this happening.  its easy enough to run the seeder.  im closing.
